export { HomePage } from './HomePage'
export { ConfigPage } from './ConfigPage'
export { TeamsPage } from './TeamsPage'
export { ResultPage } from './ResultPage'
export { NotFoundPage } from './NotFoundPage'
